name: assignment-test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  unit-test:
    runs-on: self-hosted
    container: cuaesd/aesd-autotest:24-unit-test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Make unit-test.sh executable
        run: chmod +x ./unit-test.sh
      - name: Run unit tests
        run: ./unit-test.sh

  full-test:   # Part 2
    runs-on: self-hosted
    container: cuaesd/aesd-autotest:24-assignment4-buildroot
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Run full test
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: ./full-test.sh
      - name: Cleanup
        if: always()
        run: |
          ssh-add -D
