name: assignment-test
on:
  push:
    branches:
      - '*'

jobs:
  unit-test:   # Part 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          pwd
          ls -la
          chmod +x unit-test.sh
          ./unit-test.sh

  full-test:   # Part 2
    container: cuaesd/aesd-autotest:24-assignment4-buildroot
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ./full-test.sh
